name: Injection Lockdown Test

on:
  issues:
    types: [opened]

jobs:
  untrusted-input-job:
    runs-on: ubuntu-latest
    steps:
      - name: Log Issue Title SECURE
        env:
          THE_ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          echo "New issue title is: $THE_ISSUE_TITLE"
